repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        types: [python]
        exclude: ^notebook/
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: trailing-whitespace
        types: [python]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
    - id: pyupgrade
      args: [--py39-plus]

  - repo: local
    hooks:
      - id: ruff-lint
        name: Python code linting with Ruff
        entry: uv run ruff check --fix
        language: system
        types: [python]
        exclude: ^notebook/

      - id: ruff-format
        name: Python code formatting with Ruff
        entry: uv run ruff format
        language: system
        types: [python]
        exclude: ^notebook/

  #     - id: mypy
  #       name: Python type checking with MyPy
  #       entry: uv run mypy
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       args:
  #       - "app"
  #       - "tests"
  #       exclude: ^notebook/
  # -   repo: local
  #     hooks:
  #     -   id: pyright
  #         name: pyright
  #         entry: pyright
  #         language: system
  #         types: [python]
