[project]
name = "all-rl-algorithms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.2.0",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "torch>=2.8.0",
]
