["Blinker"]
alive_cells = [[1, 0], [1, 1], [1, 2]]

["Glider"]
alive_cells = [[0, 1], [1, 2], [2, 0], [2, 1], [2, 2]]

["Toad"]
alive_cells = [[2, 1], [2, 2], [2, 3], [3, 0], [3, 1], [3, 2]]

["Beacon"]
alive_cells = [[0, 0], [0, 1], [1, 0], [2, 3], [3, 2], [3, 3]]

["Block"]
alive_cells = [[0, 0], [0, 1], [1, 0], [1, 1]]
